# Use the official Python image as the base image
FROM python:3.11.4

# Install system dependencies
RUN apt-get update && apt-get install -y libgl1-mesa-glx

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the required Python packages
RUN pip install -r requirements.txt

# Copy the rest of the application source code into the container
COPY ./app_skin_cancer .

# Set the working directory to the Flask app folder
WORKDIR /app/app_skin_cancer

# Expose port 5000 to the outside world
EXPOSE 5000

# Define the command to run the application
# CMD ["python", "app_skin_cancer.py"]
CMD ["gunicorn", "--timeout", "40000", "--bind", "0.0.0.0:5000", "app_skin_cancer:app"]
